name: 发生的客户反馈防守打法客户是否离开的胡椒粉和付额外为我不问饿哦接收到回复时看到发号施令方法和圣诞节粉红色的风景都舒服了舒服了地方了舒服服务辅导费反倒是
description: 一种轻量级的 websocket 的客户端。
keywords:
  - websocket
  - network
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
